config/routes.rb
Rails.application.routes.draw do
  resources :tickets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  has_attached_file :ticket_img, :styles => { :medium => "300x300>", :thumb => "100x100#" }
  validates_attachment_content_type :ticket_img, :content_type => /\Aimage\/.*\Z/
  validates_presence_of :band, :venue, :city, :date

  def get_concerts_list_by_artist(artist, venue, city)
    response = RestClient::Request.execute(method: :get, url: "https://api.setlist.fm/rest/1.0/search/setlists?artistName=#{artist}&venueName=#{venue}&cityName=#{city}", headers: {x_api_key: ENV['x_api_key'], Accept: 'application/json'})
    # response["setlist"][0]["sets"]["set"]
    response = JSON.parse(response)["setlist"][0]["sets"]["set"][0]["song"]
    #dig?
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  def index
    @tickets = Ticket.all
  end

  def show
    @ticket = Ticket.find(params[:id])
    binding.pry
    @setlist = @ticket.get_concerts_list_by_artist(@ticket.band, @ticket.venue, @ticket.city)
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      flash[:notice] = "Ticket added!"
      redirect_to tickets_path
    else
      render :new
    end
  end

  def edit
    @ticket = Ticket.find(params[:id])
  end

  def update
    @ticket= Ticket.find(params[:id])
    if @ticket.update(ticket_params)
      flash[:notice] = "Ticket updated!"
      redirect_to tickets_path
    else
      render :edit
    end
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy
    flash[:alert] = "Ticket deleted!"
    redirect_to tickets_path
  end

private
  def ticket_params
    params.require(:ticket).permit(:ticket_img, :band, :venue, :city, :date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ticket OCR</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= flash[:alert] %>
      <%= flash[:notice] %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tickets/_form.html.erb
<%= render "layouts/errors", :object => @ticket%>

<%= form_for @ticket do |f| %>
  <%= f.label :ticket_img, "Upload Ticket Image", class: 'col-sm-2 control-label' %><br>
  <%= f.file_field :ticket_img %><br>
  <%= f.label :band, "Band/Artist:", class: 'col-sm-2 control-label' %>
  <%= f.text_field :band %><br>
  <%= f.label :venue, "Venue Name:", class: 'col-sm-2 control-label' %>
  <%= f.text_field :venue %><br>
  <%= f.label :city, "City:", class: 'col-sm-2 control-label' %>
  <%= f.text_field :city %><br>
  <%= f.label :date, "Date:", class: 'col-sm-2 control-label' %>
  <%= f.date_field :date %><br>
  <%= f.submit "Add ticket", class: "btn btn-primary" %>
<% end %>

app/views/tickets/edit.html.erb
<h1>Edit Ticket</h1>

<%= render "form" %>

app/views/tickets/index.html.erb
<h1>Tickets</h1>

<% @tickets.each do |ticket| %>
  <div class="ticket">
    <%= link_to ticket.band, ticket_path(ticket) %>
    <%= image_tag(ticket.ticket_img.url(:thumb)) %>
  </div>
<% end %>

<%= link_to "Add a new concert ticket", new_ticket_path %>

app/views/tickets/new.html.erb
<h1>Upload a ticket</h1>

<%= render "form" %>

app/views/tickets/show.html.erb
<h1><%= @ticket.band %></h1>

<%= image_tag(@ticket.ticket_img.url(:medium)) %>

<h3><strong>Venue:</strong> <%= @ticket.band %> </h3>
<h3><strong>City:</strong> <%= @ticket.city %> </h3>
<h3><strong>Date:</strong> <%= @ticket.date %> </h3>

<h2>Setlist</h2>
<ul>
  <% @setlist.each do |song| %>
    <li><%= song.fetch("name") %></li>
  <% end %>
</ul>

<p><%= link_to "Edit", edit_ticket_path(@ticket) %></p>
<p><%= link_to "Delete", ticket_path(@ticket),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>


<p><%= link_to "Return to home", tickets_path %></p>